controller_limits:
  kp_min: 0.0
  kp_max: 50.0
  kd_min: 0.0
  kd_max: 5.0

joint_limits:
  FR:
    hip:    { min: -0.6, max:  0.6 }
    thigh:  { min: -2.6, max:  0   }
    calf:   { min:  0  , max:  3.7 }
  FL:
    hip:    { min: -0.6, max:  0.6 }
    thigh:  { min:  0  , max:  2.6 }
    calf:   { min: -3.7, max:  0.0 }
  RR:
    hip:    { min: -0.6, max:  0.6 }
    thigh:  { min:  0  , max:  2.6 }
    calf:   { min: -3.7, max:  0.0 }
  RL:
    hip:    { min: -0.6, max:  0.6 }
    thigh:  { min: -2.6, max:  0 }
    calf:   { min: -0  , max:  3.7 }
